### ISSUE TITLE
Accordion opening and closing animation

### ISSUE THREAD

**Issue by gouravkhunger** [gouravkhunger/AccoLib#1]
The accordion just toggles the visibility of the text for now. It would be great if the text has a sliding down animation on being visible, and a sliding up animation on being dismissed.

Check line 152 of [Accordion.kt](https://github.com/gouravkhunger/AccoLib/blob/main/accolib/src/main/java/com/gouravkhunger/accolib/widget/Accordion.kt#L152) file

**Comment by xtanion** [comment]
I can give it a try, can you assign it to me please 😄

**Comment by gouravkhunger** [comment]
Sure, go ahead :)

**Comment by gouravkhunger** [comment]
Sorry, assigned to myself by mistaked 😂

**Comment by xtanion** [comment]
@gouravkhunger  I've submitted my PR, please have a look at it, Thank You.

**Comment by xtanion** [comment]
I can add a gif or video of the sample if you want 😃

**Comment by gouravkhunger** [comment]
Sure, adding the gif would help me to merge it faster, else I have to clone and test myself 😂

**Comment by xtanion** [comment]
https://user-images.githubusercontent.com/74976752/135758271-e8aa9081-23ae-46ac-afc8-cbca72d4eb86.mp4

I have attached a sample animation.

**Comment by gouravkhunger** [comment]
Hey that's good, but the thing is I have tried this approach, the problem here is that there is duel animation.

If you slow down this animation and look at the frames, you would see that a space comes down before the actual texts is sliding down, and I wanted something that would make the text animate all on itself and make its space as it comes down. 

Right now, it is first creating some space for itself, and then showing the animation.

Thanks a lot for the PR, if you could resolve the above issue, then I would be really happy to merge it :)

**Comment by xtanion** [comment]
Sure, I'll try to fix that

**Comment by gouravkhunger** [comment]
We'll will release a new version on jitpack when we add a few more changes :)
