### ISSUE TITLE
how to set text or description through viewbinding?. As i am not getting any suggestion about any property that i can set?

### ISSUE THREAD

**Issue by Akash-github-project** [gouravkhunger/AccoLib#4]
![image](https://github.com/gouravkhunger/AccoLib/assets/84441071/292738bd-b610-4e6b-89e6-9adc5a9c1981)

**Comment by gouravkhunger** [comment]
Hi @Akash-github-project!

Sorry that the library does not have public functions that can do that. This project was the result of a messy implementation that I hacked up in a few hours back then.

I'll add them as soon as possible. But if you are interested to take this task please let me know so I can assign and help you contribute.
