### ISSUE TITLE
Allow setting title and text programmatically 

### ISSUE THREAD

**Issue by emleonstz** [gouravkhunger/AccoLib#8]
please add method for programmatically setting text when looping it like
accordion.setTitle("Hello");
accordion.setText("World");

**Comment by gouravkhunger** [comment]
Hi @emleonstz, the latest release `v1.1.2` of the library allows you to access these properties on runtime. Please update to the latest version and let me know if this solves your use case.

Here is an example from the demo app:

https://github.com/gouravkhunger/AccoLib/blob/e2c5fda28f2688cb97c78c0901346353ad8e1f96/app/src/main/java/com/gouravkhunger/accolibdemo/MainActivity.kt#L38-L46
